name: Justin Handley
favicon: null
layout_spectrum: 0.164978482760489
typography_spectrum: 0.89233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5aa1d5'
    - '#71aede'
    - '#e4eff8'
    - '#9dc7e5'
  brandStrength: 0.6167086139321327
  lightness: 0.1477815811522305
  saturation: 0.5809770368505269
  rhythmicContrast: 0.9805753228720278
purpose: []
